Removed hardcoded DB param

diff --git a/bin/oracle-sqlldr b/bin/oracle-sqlldr
--- a/bin/oracle-sqlldr
+++ b/bin/oracle-sqlldr
@@ -2,22 +2,22 @@
 
 source ./bin/check || exit 1
 
-if [ ! -f "./src/ETL/${1}.par" ]
+if [ -z "${1}" ]
 then
-  >&2 echo "File not found: ./src/ETL/${1}.par"
+  >&2 echo "No database specified"
   exit 1
 fi
 
-if [ ! -f "./src/ETL/${1}.ctl" ]
+if [ ! -f "${2}" ]
 then
-  >&2 echo "File not found: ./src/ETL/${1}.ctl"
+  >&2 echo "File not found: ${2}"
   exit 1
 fi
 
-if [ ! -f "./var/sqlldr/${1}.dat" ]
+if [ ! -f "${3}" ]
 then
-  >&2 echo "File not found: ./var/sqlldr/${1}.dat"
+  >&2 echo "File not found: ${3}"
   exit 1
 fi
 
-sqlldr /@${DBNAME} PARFILE=./src/ETL/${1}.par DATA=./var/sqlldr/${1}.dat
+sqlldr USERID=/@${1} PARFILE=${2} DATA=${3}
diff --git a/bin/oracle-sqlplus b/bin/oracle-sqlplus
--- a/bin/oracle-sqlplus
+++ b/bin/oracle-sqlplus
@@ -2,10 +2,16 @@
 
 source ./bin/check || exit 1
 
-if [ ! -f "./src/ETL/${1}.sql" ]
+if [ -z "${1}" ]
 then
-  >&2 echo "File not found: ./src/ETL/${1}.sql"
+  >&2 echo "No database specified"
   exit 1
 fi
 
-sqlplus -F -L -S /@${DBNAME} @./src/ETL/${1}.sql
+if [ ! -f "${2}" ]
+then
+  >&2 echo "File not found: ${2}"
+  exit 1
+fi
+
+sqlplus -F -L -S /@${1} @${2}
